name: gltf-creation
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
      - certifi
      - charset-normalizer
      - contourpy
      - cycler
      - fonttools
      - idna
      - kiwisolver
      - matplotlib
      - numpy
      - packaging
      - pillow
      - platformdirs
      - pooch
      - pyparsing
      - python-dateutil
      - pyvista
      - requests
      - scooby
      - six
      - typing-extensions
      - urllib3
      - vtk
