name: gltf-creation
channels:
  - defaults
dependencies:
  - python=3.11
  - notebook
  - pyproj=3.6.1
  - pip:
      - charset-normalizer
      - contourpy
      - cycler
      - fonttools
      - idna
      - karney
      - kiwisolver
      - matplotlib
      - numpy
      - nvector
      - packaging
      - pillow
      - platformdirs
      - pooch
      - pyparsing
      - pyvista
      - scipy
      - scooby
      - six
      - typing-extensions
      - vtk
